AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  GoogleApi:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: GoogleAPI
      Description: Google API SDK for Python 3
      ContentUri: lib
      RetentionPolicy: Retain
      CompatibleRuntimes:
        - python3.6
        - python3.7
        - python3.8
        - python3.9
Outputs:
    GoogleApi:
        Value: !Ref GoogleApi
        Export:
            Name: GoogleApi
